version: '3'
services:
  db:
     image: postgres:16
     container_name: postgres-container
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=1234
  backend:
    image: c_back
    build:
      context: ./backend
    container_name: store_backend_container
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  frontend:
    image: c_front
    container_name: frontend_container
    depends_on:
      - backend
    ports:
      - "5173:5173"
    build:
      context: ./frontend
