version: '3'
services:
  db:
     image: postgres:latest
     container_name: postgres-container
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=1234
  app:
    image: connection:latest
    container_name: current_joy
    build:
      context: .
    depends_on:
              - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"